# Root file for the composition.
#
# The options specific to the development should go in
# 'docker-compose.override.yml' which is automatically applied on top of this
# file when the option '-f' of docker-compose is not used

version: '2'
services:
  odoo:
    build: ./odoo/
    command: "odoo.py --load=web,connector"
    depends_on:
      - db
    volumes:
      - "data-odoo:/data/odoo"
    environment:
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=odoodb
      - ADMIN_PASSWD=
      - RUNNING_ENV=dev
      - ODOO_CONNECTOR_CHANNELS=root:4

  db:
    image: camptocamp/postgresql:pg9.5-latest
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PG_SYSTEM_SHARED_BUFFERS=256MB
      - PG_SYSTEM_MAINTENANCE_WORK_MEM=256MB
      - PG_SYSTEM_WAL_BUFFERS=8MB
      - PG_SYSTEM_EFFECTIVE_CACHE_SIZE=1024MB
    volumes:
      - "data-db:/var/lib/postgresql/data"

  nginx:
    image: camptocamp/odoo-nginx:9.0
    depends_on:
      - odoo

  prestashop:
    image: prestashop/prestashop:1.6
    depends_on:
      - mysql
    environment:
      - DB_SERVER=mysql
      - PS_FOLDER_ADMIN=backoffice
      - PS_FOLDER_INSTALL=setup
      - PS_INSTALL_AUTO=1

  mysql:
    image: mysql:5.6
    volumes:
      - "data-mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=admin

volumes:
  data-odoo:
  data-db:
  data-mysql:
